### ISSUE TITLE
Incorporate New "Pay With: Types

### ISSUE THREAD

**Issue by yashlinmaistry** [brascene/rn-apple-pay-button#1]
Firstly, I appreciate the  library! it's a massive help.

Apple has release new "Pay with" types (Book & checkout, subscribe)

It would be great if you can add it into the library, with a fallback if the device is below ios 12 

Cheers

**Comment by brascene** [comment]
Hi there, thanks and I'm glad you find it useful.
Regarding your question, are you thinking about this? 

<img width="201" alt="Screen Shot 2020-03-26 at 3 18 38 PM" src="https://user-images.githubusercontent.com/20214107/77657101-1b69d980-6f75-11ea-951c-fc33291347d4.png">

**Comment by yashlinmaistry** [comment]
I was thinking about the new ones on Apples website 

(https://developer.apple.com/design/human-interface-guidelines/apple-pay/overview/buttons-and-marks/)

The new types
PKPaymentButtonTypeBook
PKPaymentButtonTypeCheckout
PKPaymentButtonTypeSubscribe

**Comment by brascene** [comment]
I've just quickly added those missing types, and I'm closing this issue.
Thanks!

**Comment by indigomelody** [comment]
There are new payment types (such as Top up). Can we get them added to this module please?
