### ISSUE TITLE
Invariant Violation: requireNativeComponent: "APButton" was not found

### ISSUE THREAD

**Issue by ruckk** [brascene/rn-apple-pay-button#2]
Hi,

I get the above error after Installing and linking the package, what am i missing?

**Comment by JollyGolf** [comment]
+1 right now

**Comment by JollyGolf** [comment]
> Hi,
> 
> I get the above error after Installing and linking the package, what am i missing?

I solved this issue. Just go to XCode and Clean Project.

**Comment by brascene** [comment]
Hi there, it's definitely related with installation or linking, make sure to run pod install, and to link the project.

**Comment by ruckk** [comment]
Reinstalling the pods solved it. Thanks!
