### ISSUE TITLE
Change the cornerRadius

### ISSUE THREAD

**Issue by Lazymondaysunday** [brascene/rn-apple-pay-button#3]
Looks like that you are able to change the cornerRadius of the native button, any way to do that currently with this?

https://developer.apple.com/documentation/passkit/pkpaymentbutton/2999416-cornerradius

**Comment by KaSSii** [comment]
Agree with this. This appears to be the only thing missing from an otherwise good (and emerging) react native package

**Comment by kdzapp** [comment]
+1

**Comment by brascene** [comment]
Thanks guys for pointing out, it's available now :)
