### ISSUE TITLE
Version 1.1.0 doesn't build in Xcode 12.0.1

### ISSUE THREAD

**Issue by rkrueger11** [brascene/rn-apple-pay-button#5]
[Shows the following errors](https://cln.sh/1MiJeu)

**Comment by Goldziher** [comment]
yes, this fails to build. A shame...

**Comment by tafty** [comment]
I've created a fork and fixed the build issue here:

https://github.com/tafty/rn-apple-pay-button

I'm not a native iOS developer and am not familiar with Objective-C but the fixes I've implemented do work.

I've also created a pull request here:

https://github.com/brascene/rn-apple-pay-button/pull/7

**Comment by brascene** [comment]
Thanks, merged.
